### PR TITLE
Feature/landing refactor

### PR DESCRIPTION
**Pull request by iworkinmysleep**
This feature is based on the deliverable of 'Refactoring on the FE for the User Flow'.  I put the page outside of the switch and routes for now so that everyone could see the page and review.

### CODE REVIEW

**Review by abhitsahota — DISMISSED** [review]
Code looks good and follow best practices. Very helpful to get us on the right foot with a cleaner landing page. 
Since this PR was submitted prior to the PR lesson I believe it should be approved despite the adherence to the rubric components like description.

**Comment by ChitownCoder** [comment]
The code looks very good, code is clean and has best practice in mind, would be nice to have more comments, I also agree with Abhit, we are on the right path with a cleaner landing page.

I think it's imperative that this needs to be approved as well.

**Review by ChitownCoder — DISMISSED** [review]
The code looks very good, code is clean and has best practice in mind, would be nice to have more comments, I also agree with Abhit, we are on the right path with a cleaner landing page.

I think it's imperative that this needs to be approved as well.

**Comment by abhitsahota** [comment]
[As a user, I want to easily navigate from search to the city dashboard view so that I can easily retrieve and understand the city information. [Refactor landing page]](https://trello.com/c/uMZzIzgD/10-as-a-user-i-want-to-easily-navigate-from-search-to-the-city-dashboard-view-so-that-i-can-easily-retrieve-and-understand-the-city)

**Comment by abhitsahota** [comment]
Seems as though this PR won't pass because of the failed tests/checks which are from the legacy code. Anyway we could get around this or will this be a blocker to PRs? @tinomen 
image

**Comment by tinomen** [comment]
You can run tests and eslint locally so they can be fixed. Check your package.json

**Comment by iworkinmysleep** [comment]
Anthony pushed a repo that was passing all tests so I deleted this branch and pulled the main after his branch was merged.  I will start a new branch and add the user landing folder to that branch.

**Pull request closed without merging**
